name: bitsdojo_window_windows
description: Windows implementation of the bitsdojo_window plugin.
version: 0.1.3
homepage: https://www.bitsdojo.com
repository: https://github.com/bitsdojo/bitsdojo_window

publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  bitsdojo_window_platform_interface:
    path: ../bitsdojo_window_platform_interface
  win32: ^2.5.2
  ffi: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      windows:
        pluginClass: BitsdojoWindowPlugin